modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/jaacksondev/etched/issues"
license = "GPLv3"

[[mods]]
modId = "etched"
version = "${version}"
displayName = "Etched"
updateJSONURL = "https://raw.githubusercontent.com/jaacksondev/etched/main/update.json"
authors = "Jackson, Ocelot, Farcr"
credits = "Astrazoey (for creating the etching sound)"
description = "A new way to play music"

[modproperties.etched]
catalogueItemIcon="etched:album_jukebox"

[[dependencies.etched]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.etched]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"