modLoader = "javafml"
loaderVersion = "[36,)"
issueTrackerURL = "https://github.com/JacksonPlayz/etched/issues"
license = "GPLv3"

[[mods]]
modId = "etched"
version = "${version}"
displayName = "Etched"
updateJSONURL = "https://raw.githubusercontent.com/JacksonPlayz/etched/main/update.json"
authors = "Jackson, Ocelot"
description = "Create custom music discs!"

[[dependencies.etched]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.etched]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"